baseURL = "https://www.icl.site/"
languageCode = "zh-cn"
defaultContentLanguage = "cn"
title = "ICL"
theme = "github-style"
paginate = 5
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "xiaqiankun"
  description = "Ë∫∫Âπ≥Âç≥Ê≠£‰πâ„ÄÇNothing is true, everything is permitted"
  github = "xqk"
  email = "xiaqiankun@outlook.com"
  url = "https://www.icl.com"
  keywords = "ÊúâÈí±"
  rss = true
  lastmod = true
  userStatusEmoji = "üòÄ"
  location = "China"
  favicon = "/images/favicon.png"
  avatar = ""
  enableGitalk = true

    [params.gitalk]
      clientID = "b61411f2bdbd985b3da2"
      clientSecret = "edb4128727849400b78e389aa69492c8d718de9d"
      repo = "repo"
      owner = "xqk"
      admin = "xqk"
      id = "location.pathname"
      labels = "gitalk"
      perPage = 15
      pagerDirection = "last"
      createIssueManually = true
      distractionFreeMode = false

  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
